from tkinter import Tk,messagebox,Entry,Menu,Canvas,PhotoImage,Label
from Integral import Integral
from Aposter_Error import Aposter_Error
from Apriori_Error import Apriori_Error
def Integral_click(choice):
    messagebox.showinfo("Result","%.5f"%Integral(choice,str(txtFun.get()),float(txtA.get()),float(txtB.get()),int(txtN.get()),float(txtE.get())))
def Aposter_click(choice):
    messagebox.showinfo("Result","%.5f"%Aposter_Error(choice,str(txtFun.get()),float(txtA.get()),float(txtB.get()),int(txtN.get())))
def Apriori_click(choice):
    messagebox.showinfo("Result","%.5f"%Apriori_Error(choice,str(txtFun.get()),float(txtA.get()),float(txtB.get()),int(txtN.get())))
form = Tk()
form.title("LAB №11")
form.geometry('500x250')
mainmenu = Menu() 
form.config(menu=mainmenu)
can = Canvas(form)
can.pack()
img = PhotoImage(file="int.png")
can.create_image(100, 100, image=img, anchor="nw")
lblA = Label(form,text = "a").place(x=10,y=180)
txtA = Entry(form,width =3)
txtA.insert(0,'1')
txtA.place(x=170,y=180)
lblB = Label(form,text = "b").place(x=10,y=80)
txtB = Entry(form,width =3)
txtB.insert(0,'2.8')
txtB.place(x=170,y=80)
lblN = Label(form,text = "n").place(x=10,y=10)
txtN = Entry(form,width =3)
txtN.insert(0,'12')
txtN.place(x=60,y=10)
lblE = Label(form,text = "Accuracy").place(x=10,y=30)
txtE = Entry(form,width =10)
txtE.insert(0,'0.00001')
txtE.place(x=100,y=30)
lblFun = Label(form,text = "function").place(x=10,y=130)
lbldx = Label(form,text = "dx").place(x=400,y=130)
txtFun = Entry(form,width =30)
txtFun.insert(0,'(4.2*x*x-8.1)/(x*x*x+3.8)')
txtFun.place(x=200,y=130)
Integralmenu = Menu(tearoff=0)
Integralmenu.add_command(label="Simpson", command = lambda: Integral_click(1))
Integralmenu.add_command(label="Trapezium", command = lambda: Integral_click(2))
Integralmenu.add_command(label="Left Rectangles", command = lambda: Integral_click(3))
Integralmenu.add_command(label="Right Rectangles", command = lambda: Integral_click(4))
Integralmenu.add_command(label="Medium Rectangles", command = lambda: Integral_click(5))
Apostermenu = Menu(tearoff=0)
Apostermenu.add_command(label="Simpson" , command = lambda: Aposter_click(1))
Apostermenu.add_command(label="Trapezium", command = lambda: Aposter_click(2))
Apostermenu.add_command(label="Left Rectangles", command = lambda: Aposter_click(3))
Apostermenu.add_command(label="Right Rectangles", command = lambda: Aposter_click(4))
Apostermenu.add_command(label="Medium Rectangles", command = lambda: Aposter_click(5))
Apriorimenu = Menu(tearoff=0)
Apriorimenu.add_command(label="Simpson" , command = lambda: Apriori_click(1))
Apriorimenu.add_command(label="Trapezium", command = lambda: Apriori_click(2))
Apriorimenu.add_command(label="Left Rectangles", command = lambda: Apriori_click(3))
Apriorimenu.add_command(label="Right Rectangles", command = lambda: Apriori_click(4))
Apriorimenu.add_command(label="Medium Rectangles", command = lambda: Apriori_click(5))
mainmenu.add_cascade(label="Integral", menu=Integralmenu)
mainmenu.add_cascade(label="Aposter Error", menu=Apostermenu)
mainmenu.add_cascade(label="Apriori Error", menu=Apriorimenu)
form.mainloop()